# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=10)),
                ('box_color', models.CharField(choices=[('red', 'red'), ('blu', 'blue'), ('gre', 'green'), ('yel', 'yellow')], default='red', max_length=3)),
                ('mass', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
