# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st_0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st_0.box')),
            ],
        ),
    ]
